# Test config to reproduce the old mars-dip_nv-dip.npz results.
# Uses horizon-masked variant of the MARS CSA2022 beam.
run_name: "test-compare-old-mars-dip-nv-dip"

beams: [mars-csa2022-dip-horizon, nv-dip]

svd:
  n_singular_values: 800

output:
  generate_notebook: false
